In [4]:
import numpy as np
import utility

from full_qubo_solver import FullQuboSolver

In [6]:
n = 5
m = 2
seed = 1543

In [7]:
instance, xc, yc = utility.generate_vrp_instance(n, seed)

In [8]:
print(instance)
print(xc)
print(yc)

[[ 0.          4.27004888  3.03023376 26.01875627  6.82521534 10.89540557]
 [ 4.27004888  0.         11.34000725 50.87753159  1.37726708 28.08723873]
 [ 3.03023376 11.34000725  0.         16.15307858 17.73198146  4.76500506]
 [26.01875627 50.87753159 16.15307858  0.         58.76742563  3.44295045]
 [ 6.82521534  1.37726708 17.73198146 58.76742563  0.         34.83384593]
 [10.89540557 28.08723873  4.76500506  3.44295045 34.83384593  0.        ]]
[ 0.51003914  2.55963937 -0.64283509 -4.57068577  2.98724481 -2.72584275]
[ 1.05534574  0.79231007 -0.24892217  0.60258683  1.88520561  0.40382905]


In [9]:
variables = np.array([[['x.{}.{}.{}'.format(i, j, k) for k in range(1, n + 1)]
                                    for j in range(n + 1)] for i in range(1, m + 1)])
print(variables)
print(variables[1,2,3])

[[['x.1.0.1' 'x.1.0.2' 'x.1.0.3' 'x.1.0.4' 'x.1.0.5']
  ['x.1.1.1' 'x.1.1.2' 'x.1.1.3' 'x.1.1.4' 'x.1.1.5']
  ['x.1.2.1' 'x.1.2.2' 'x.1.2.3' 'x.1.2.4' 'x.1.2.5']
  ['x.1.3.1' 'x.1.3.2' 'x.1.3.3' 'x.1.3.4' 'x.1.3.5']
  ['x.1.4.1' 'x.1.4.2' 'x.1.4.3' 'x.1.4.4' 'x.1.4.5']
  ['x.1.5.1' 'x.1.5.2' 'x.1.5.3' 'x.1.5.4' 'x.1.5.5']]

 [['x.2.0.1' 'x.2.0.2' 'x.2.0.3' 'x.2.0.4' 'x.2.0.5']
  ['x.2.1.1' 'x.2.1.2' 'x.2.1.3' 'x.2.1.4' 'x.2.1.5']
  ['x.2.2.1' 'x.2.2.2' 'x.2.2.3' 'x.2.2.4' 'x.2.2.5']
  ['x.2.3.1' 'x.2.3.2' 'x.2.3.3' 'x.2.3.4' 'x.2.3.5']
  ['x.2.4.1' 'x.2.4.2' 'x.2.4.3' 'x.2.4.4' 'x.2.4.5']
  ['x.2.5.1' 'x.2.5.2' 'x.2.5.3' 'x.2.5.4' 'x.2.5.5']]]
x.2.2.4


In [10]:
obj_linear_a = {variables[a, b, 0]: instance[0, b] for a in range(m) for b in range(1, n + 1)}
obj_linear_b = {variables[a, b, -1]: instance[b, 0] for a in range(m) for b in range(1, n + 1)}
print(obj_linear_a)
print(obj_linear_b)

{'x.1.1.1': 4.270048879604721, 'x.1.2.1': 3.0302337646881803, 'x.1.3.1': 26.018756268033645, 'x.1.4.1': 6.825215339954393, 'x.1.5.1': 10.895405571795322, 'x.2.1.1': 4.270048879604721, 'x.2.2.1': 3.0302337646881803, 'x.2.3.1': 26.018756268033645, 'x.2.4.1': 6.825215339954393, 'x.2.5.1': 10.895405571795322}
{'x.1.1.5': 4.270048879604721, 'x.1.2.5': 3.0302337646881803, 'x.1.3.5': 26.018756268033645, 'x.1.4.5': 6.825215339954393, 'x.1.5.5': 10.895405571795322, 'x.2.1.5': 4.270048879604721, 'x.2.2.5': 3.0302337646881803, 'x.2.3.5': 26.018756268033645, 'x.2.4.5': 6.825215339954393, 'x.2.5.5': 10.895405571795322}


In [11]:
center = (22.549134075168105, 88.35608616688717)
locs = [
    (22.565923, 88.368951),
    (22.57276655444997, 88.38948573982795),
    (22.54077163135614, 88.3963315562282),
    (22.518144017282523, 88.34885076420595),
    (22.546356896470648, 88.34243962154214),
]
labels = {
    0 : "St. Xavier's College",
    1 : "Sealdah",
    2 : "Phoolbagan",
    3 : "Science City",
    4 : "Lake Mall",
    5 : "Victoria Memorial",
}
xs = np.zeros(6)
ys = np.zeros(6)
i = 1
for loc in locs:
    ys[i] = (loc[0] - center[0]) * 500
    xs[i] = (loc[1] - center[1]) * 500
    i += 1

print(xs)
print(ys)

[ 0.          6.43241656 16.69978647 20.12269467 -3.61770134 -6.82327267]
[  0.           8.39446242  11.81623964  -4.18122191 -15.49502894
  -1.38858935]


In [12]:
inst = np.zeros((n + 1, n + 1))
for ii in range(6):
        for jj in range(ii + 1, 6):
            inst[ii, jj] = (xs[ii] - xs[jj]) ** 2 + (ys[ii] - ys[jj]) ** 2
            inst[jj, ii] = inst[ii, jj]
        
print(inst)

[[   0.          111.84298201  418.50638741  422.40545743  253.18368493
    48.48523034]
 [ 111.84298201    0.          117.12744433  345.57155101  671.71266712
   271.42139876]
 [ 418.50638741  117.12744433    0.          267.63507649 1158.7057026
   727.70182009]
 [ 422.40545743  345.57155101  267.63507649    0.          691.60863243
   733.88395265]
 [ 253.18368493  671.71266712 1158.7057026   691.60863243    0.
   209.26732558]
 [  48.48523034  271.42139876  727.70182009  733.88395265  209.26732558
     0.        ]]


In [ ]:
fqs = FullQuboSolver(n, m, inst)
fqs.solve(solver='leap')

In [ ]:
fqs.visualize(xs, ys, labels)